## Основы Pandas
- Описание датафрейма
- Чтение и выгрузка данных
- Сортировка

## Задание
- Скачать данные с Kaggle (https://www.kaggle.com/datasets)
- Сортировать данные и некотрый срез (head, tail) сохранить как csv

In [2]:
import pandas as pd

In [9]:
df = pd.read_csv('../data/raw/E-commerce_Delivery_Shipping_Data_2026.csv')

In [12]:
df.head(10)

,order_id,order_date,customer_id,customer_segment,customer_city,customer_country,warehouse_id,warehouse_city,product_category,product_weight_kg,...,package_size,payment_method,order_priority,weather_condition,customer_rating,return_requested,return_reason,delivery_attempts,warehouse_processing_hours,tracking_status
0,ORD-000001,2026-11-15,CUS-002353,Small Business,Tokyo,Japan,WH-004,Toronto,Home & Kitchen,8.23,...,Large,Digital Wallet,Normal,Snow,3,Yes,Late Delivery,2,25.1,Delivered
1,ORD-000002,2026-04-08,CUS-003258,Consumer,Vancouver,Canada,WH-007,Paris,Beauty,0.10,...,Small,Debit Card,Normal,Cloudy,5,No,NaN,1,25.9,Delivered
2,ORD-000003,2026-01-05,CUS-001221,Consumer,Houston,United States,WH-005,London,Home & Kitchen,5.51,...,Large,Debit Card,Low,Snow,4,Yes,Product Defect,1,31.5,Delivered
3,ORD-000004,2026-05-29,CUS-001717,Small Business,Delhi,India,WH-002,Los Angeles,Grocery,3.75,...,Large,Debit Card,Normal,Snow,3,No,NaN,1,12.6,In Transit
4,ORD-000005,2026-02-22,CUS-000716,Small Business,Nagoya,Japan,WH-006,Berlin,Beauty,0.10,...,Small,Credit Card,Normal,Storm,2,No,NaN,1,24.9,Delivered
5,ORD-000006,2026-03-06,CUS-005749,Consumer,Brisbane,Australia,WH-002,Los Angeles,Toys,0.76,...,Medium,Debit Card,Low,Extreme Heat,3,No,NaN,1,32.2,Delivered
6,ORD-000007,2026-07-10,CUS-002409,Small Business,Ottawa,Canada,WH-003,Chicago,Grocery,4.81,...,Large,Bank Transfer,Normal,Rain,3,No,NaN,1,21.0,Delivered
7,ORD-000008,2026-12-03,CUS-003537,Consumer,Los Angeles,United States,WH-004,Toronto,Electronics,3.51,...,Large,Cash on Delivery,Normal,Snow,2,No,NaN,1,21.2,Delivered
8,ORD-000009,2026-12-18,CUS-004446,Consumer,Phoenix,United States,WH-002,Los Angeles,Grocery,2.09,...,Large,Credit Card,High,Clear,4,No,NaN,1,12.7,Delivered
9,ORD-000010,2026-11-05,CUS-005134,Enterprise,Dusseldorf,Germany,WH-002,Los Angeles,Home & Kitchen,0.10,...,Small,Debit Card,Normal,Rain,2,No,NaN,1,15.1,Delivered

In [13]:
df.tail()

,order_id,order_date,customer_id,customer_segment,customer_city,customer_country,warehouse_id,warehouse_city,product_category,product_weight_kg,...,package_size,payment_method,order_priority,weather_condition,customer_rating,return_requested,return_reason,delivery_attempts,warehouse_processing_hours,tracking_status
49995,ORD-049996,2026-09-05,CUS-004163,Small Business,Leipzig,Germany,WH-001,New York,Electronics,0.86,...,Medium,Digital Wallet,High,Cloudy,4,No,NaN,2,9.1,Delivered
49996,ORD-049997,2026-12-07,CUS-004322,Consumer,London,United Kingdom,WH-005,London,Toys,0.27,...,Small,Cash on Delivery,Normal,Cloudy,4,No,NaN,1,8.9,Delivered
49997,ORD-049998,2026-11-14,CUS-000699,Enterprise,San Diego,United States,WH-001,New York,Automotive,7.76,...,Oversized,Credit Card,Low,Clear,3,Yes,Late Delivery,1,5.5,Delivered
49998,ORD-049999,2026-09-02,CUS-004696,Consumer,London,United Kingdom,WH-007,Paris,Books,1.10,...,Medium,PayPal,Low,Snow,3,No,NaN,1,45.4,Delivered
49999,ORD-050000,2026-04-11,CUS-000955,Consumer,Sharjah,United Arab Emirates,WH-001,New York,Fashion,1.36,...,Large,Digital Wallet,High,Cloudy,2,No,NaN,1,11.4,Delivered

In [14]:
df.shape

(50000, 30)

In [15]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'customer_segment',
       'customer_city', 'customer_country', 'warehouse_id', 'warehouse_city',
       'product_category', 'product_weight_kg', 'order_value_usd',
       'shipping_method', 'carrier', 'distance_km', 'promised_delivery_days',
       'actual_delivery_days', 'delivery_status', 'late_delivery',
       'delivery_delay_days', 'shipping_cost_usd', 'package_size',
       'payment_method', 'order_priority', 'weather_condition',
       'customer_rating', 'return_requested', 'return_reason',
       'delivery_attempts', 'warehouse_processing_hours', 'tracking_status'],
      dtype='object')

In [17]:
for column in df.columns:
    print(f'Столбец: {column}')

Столбец: order_id
Столбец: order_date
Столбец: customer_id
Столбец: customer_segment
Столбец: customer_city
Столбец: customer_country
Столбец: warehouse_id
Столбец: warehouse_city
Столбец: product_category
Столбец: product_weight_kg
Столбец: order_value_usd
Столбец: shipping_method
Столбец: carrier
Столбец: distance_km
Столбец: promised_delivery_days
Столбец: actual_delivery_days
Столбец: delivery_status
Столбец: late_delivery
Столбец: delivery_delay_days
Столбец: shipping_cost_usd
Столбец: package_size
Столбец: payment_method
Столбец: order_priority
Столбец: weather_condition
Столбец: customer_rating
Столбец: return_requested
Столбец: return_reason
Столбец: delivery_attempts
Столбец: warehouse_processing_hours
Столбец: tracking_status

In [18]:
df.dtypes

order_id                       object
order_date                     object
customer_id                    object
customer_segment               object
customer_city                  object
customer_country               object
warehouse_id                   object
warehouse_city                 object
product_category               object
product_weight_kg             float64
order_value_usd               float64
shipping_method                object
carrier                        object
distance_km                   float64
promised_delivery_days          int64
actual_delivery_days            int64
delivery_status                object
late_delivery                  object
delivery_delay_days             int64
shipping_cost_usd             float64
package_size                   object
payment_method                 object
order_priority                 object
weather_condition              object
customer_rating                 int64
return_requested               object
return_reason                  object
delivery_attempts               int64
warehouse_processing_hours    float64
tracking_status                object
dtype: object

In [19]:
dict(df.dtypes)

{'order_id': dtype('O'),
 'order_date': dtype('O'),
 'customer_id': dtype('O'),
 'customer_segment': dtype('O'),
 'customer_city': dtype('O'),
 'customer_country': dtype('O'),
 'warehouse_id': dtype('O'),
 'warehouse_city': dtype('O'),
 'product_category': dtype('O'),
 'product_weight_kg': dtype('float64'),
 'order_value_usd': dtype('float64'),
 'shipping_method': dtype('O'),
 'carrier': dtype('O'),
 'distance_km': dtype('float64'),
 'promised_delivery_days': dtype('int64'),
 'actual_delivery_days': dtype('int64'),
 'delivery_status': dtype('O'),
 'late_delivery': dtype('O'),
 'delivery_delay_days': dtype('int64'),
 'shipping_cost_usd': dtype('float64'),
 'package_size': dtype('O'),
 'payment_method': dtype('O'),
 'order_priority': dtype('O'),
 'weather_condition': dtype('O'),
 'customer_rating': dtype('int64'),
 'return_requested': dtype('O'),
 'return_reason': dtype('O'),
 'delivery_attempts': dtype('int64'),
 'warehouse_processing_hours': dtype('float64'),
 'tracking_status': dtype('O')}

In [36]:
for column, dtype in (df.dtypes).items():
    print(f'Столбец: {column} с типом {dtype}')

Столбец: order_id с типом object
Столбец: order_date с типом object
Столбец: customer_id с типом object
Столбец: customer_segment с типом object
Столбец: customer_city с типом object
Столбец: customer_country с типом object
Столбец: warehouse_id с типом object
Столбец: warehouse_city с типом object
Столбец: product_category с типом object
Столбец: product_weight_kg с типом float64
Столбец: order_value_usd с типом float64
Столбец: shipping_method с типом object
Столбец: carrier с типом object
Столбец: distance_km с типом float64
Столбец: promised_delivery_days с типом int64
Столбец: actual_delivery_days с типом int64
Столбец: delivery_status с типом object
Столбец: late_delivery с типом object
Столбец: delivery_delay_days с типом int64
Столбец: shipping_cost_usd с типом float64
Столбец: package_size с типом object
Столбец: payment_method с типом object
Столбец: order_priority с типом object
Столбец: weather_condition с типом object
Столбец: customer_rating с типом int64
Столбец: return_requested с типом object
Столбец: return_reason с типом object
Столбец: delivery_attempts с типом int64
Столбец: warehouse_processing_hours с типом float64
Столбец: tracking_status с типом object

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 30 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   order_id                    50000 non-null  object
 1   order_date                  50000 non-null  object
 2   customer_id                 50000 non-null  object
 3   customer_segment            50000 non-null  object
 4   customer_city               50000 non-null  object
 5   customer_country            50000 non-null  object
 6   warehouse_id                50000 non-null  object
 7   warehouse_city              50000 non-null  object
 8   product_category            50000 non-null  object
 9   product_weight_kg           50000 non-null  float64
 10  order_value_usd             50000 non-null  float64
 11  shipping_method             50000 non-null  object
 12  carrier                     50000 non-null  object
 13  distance_km                 50000 non-null  float64
 14  promised_delivery_days      50000 non-null  int64
 15  actual_delivery_days        50000 non-null  int64
 16  delivery_status             50000 non-null  object
 17  late_delivery               50000 non-null  object
 18  delivery_delay_days         50000 non-null  int64
 19  shipping_cost_usd           50000 non-null  float64
 20  package_size                50000 non-null  object
 21  payment_method              50000 non-null  object
 22  order_priority              50000 non-null  object
 23  weather_condition           50000 non-null  object
 24  customer_rating             50000 non-null  int64
 25  return_requested            50000 non-null  object
 26  return_reason               8625 non-null   object
 27  delivery_attempts           50000 non-null  int64
 28  warehouse_processing_hours  50000 non-null  float64
 29  tracking_status             50000 non-null  object
dtypes: float64(5), int64(5), object(20)
memory usage: 11.4+ MB

In [38]:
df.describe()

,product_weight_kg,order_value_usd,distance_km,promised_delivery_days,actual_delivery_days,delivery_delay_days,shipping_cost_usd,customer_rating,delivery_attempts,warehouse_processing_hours
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,2.255028,177.917107,2496.778802,7.197700,8.345940,1.281080,120.515538,3.371840,1.169860,14.412430
std,3.694952,291.600047,1774.633152,3.680229,4.644353,1.679527,108.680030,0.998777,0.390756,9.924904
min,0.100000,10.000000,40.000000,0.000000,0.000000,0.000000,4.050000,1.000000,1.000000,1.000000
25%,0.320000,28.720000,1086.775000,4.000000,5.000000,0.000000,40.640000,3.000000,1.000000,6.600000
50%,0.930000,76.840000,2182.800000,6.000000,8.000000,1.000000,82.970000,3.000000,1.000000,11.900000
75%,2.610000,173.162500,3592.475000,11.000000,12.000000,2.000000,167.422500,4.000000,1.000000,20.700000
max,52.190000,3530.730000,9553.600000,15.000000,27.000000,13.000000,500.000000,5.000000,3.000000,48.000000

In [39]:
type(1)

int

In [40]:
type('Hello')

str

In [41]:
type(1.34)

float

In [42]:
type(df)

pandas.core.frame.DataFrame

In [44]:
df['product_weight_kg']

0        8.23
1        0.10
2        5.51
3        3.75
4        0.10
         ...
49995    0.86
49996    0.27
49997    7.76
49998    1.10
49999    1.36
Name: product_weight_kg, Length: 50000, dtype: float64

In [45]:
type(df['product_weight_kg'])

pandas.core.series.Series

In [48]:
df.head()

,order_id,order_date,customer_id,customer_segment,customer_city,customer_country,warehouse_id,warehouse_city,product_category,product_weight_kg,...,package_size,payment_method,order_priority,weather_condition,customer_rating,return_requested,return_reason,delivery_attempts,warehouse_processing_hours,tracking_status
0,ORD-000001,2026-11-15,CUS-002353,Small Business,Tokyo,Japan,WH-004,Toronto,Home & Kitchen,8.23,...,Large,Digital Wallet,Normal,Snow,3,Yes,Late Delivery,2,25.1,Delivered
1,ORD-000002,2026-04-08,CUS-003258,Consumer,Vancouver,Canada,WH-007,Paris,Beauty,0.10,...,Small,Debit Card,Normal,Cloudy,5,No,NaN,1,25.9,Delivered
2,ORD-000003,2026-01-05,CUS-001221,Consumer,Houston,United States,WH-005,London,Home & Kitchen,5.51,...,Large,Debit Card,Low,Snow,4,Yes,Product Defect,1,31.5,Delivered
3,ORD-000004,2026-05-29,CUS-001717,Small Business,Delhi,India,WH-002,Los Angeles,Grocery,3.75,...,Large,Debit Card,Normal,Snow,3,No,NaN,1,12.6,In Transit
4,ORD-000005,2026-02-22,CUS-000716,Small Business,Nagoya,Japan,WH-006,Berlin,Beauty,0.10,...,Small,Credit Card,Normal,Storm,2,No,NaN,1,24.9,Delivered

In [53]:
df_2 = df.set_index(['order_id'])

In [54]:
df_2.head()

,order_date,customer_id,customer_segment,customer_city,customer_country,warehouse_id,warehouse_city,product_category,product_weight_kg,order_value_usd,...,package_size,payment_method,order_priority,weather_condition,customer_rating,return_requested,return_reason,delivery_attempts,warehouse_processing_hours,tracking_status
order_id,,,,,,,,,,,,,,,,,,,,,
ORD-000001,2026-11-15,CUS-002353,Small Business,Tokyo,Japan,WH-004,Toronto,Home & Kitchen,8.23,10.39,...,Large,Digital Wallet,Normal,Snow,3,Yes,Late Delivery,2,25.1,Delivered
ORD-000002,2026-04-08,CUS-003258,Consumer,Vancouver,Canada,WH-007,Paris,Beauty,0.10,117.69,...,Small,Debit Card,Normal,Cloudy,5,No,NaN,1,25.9,Delivered
ORD-000003,2026-01-05,CUS-001221,Consumer,Houston,United States,WH-005,London,Home & Kitchen,5.51,335.23,...,Large,Debit Card,Low,Snow,4,Yes,Product Defect,1,31.5,Delivered
ORD-000004,2026-05-29,CUS-001717,Small Business,Delhi,India,WH-002,Los Angeles,Grocery,3.75,10.57,...,Large,Debit Card,Normal,Snow,3,No,NaN,1,12.6,In Transit
ORD-000005,2026-02-22,CUS-000716,Small Business,Nagoya,Japan,WH-006,Berlin,Beauty,0.10,31.37,...,Small,Credit Card,Normal,Storm,2,No,NaN,1,24.9,Delivered

In [55]:
df_2['product_weight_kg']

order_id
ORD-000001    8.23
ORD-000002    0.10
ORD-000003    5.51
ORD-000004    3.75
ORD-000005    0.10
              ...
ORD-049996    0.86
ORD-049997    0.27
ORD-049998    7.76
ORD-049999    1.10
ORD-050000    1.36
Name: product_weight_kg, Length: 50000, dtype: float64

In [57]:
type(8.23)

float

In [60]:
print(df['product_weight_kg'][0])

8.23

In [61]:
type(df['product_weight_kg'][0])

numpy.float64

In [65]:
df[['customer_id', 'product_weight_kg']]

      customer_id  product_weight_kg
0      CUS-002353               8.23
1      CUS-003258               0.10
2      CUS-001221               5.51
3      CUS-001717               3.75
4      CUS-000716               0.10
...           ...                ...
49995  CUS-004163               0.86
49996  CUS-004322               0.27
49997  CUS-000699               7.76
49998  CUS-004696               1.10
49999  CUS-000955               1.36

[50000 rows x 2 columns]

In [68]:
df[['product_weight_kg']]

       product_weight_kg
0                   8.23
1                   0.10
2                   5.51
3                   3.75
4                   0.10
...                  ...
49995               0.86
49996               0.27
49997               7.76
49998               1.10
49999               1.36

[50000 rows x 1 columns]

In [72]:
df.sort_values(by='product_weight_kg').head(5)

,order_id,order_date,customer_id,customer_segment,customer_city,customer_country,warehouse_id,warehouse_city,product_category,product_weight_kg,...,package_size,payment_method,order_priority,weather_condition,customer_rating,return_requested,return_reason,delivery_attempts,warehouse_processing_hours,tracking_status
21176,ORD-021177,2026-10-23,CUS-002000,Consumer,Milan,Italy,WH-003,Chicago,Office Supplies,0.1,...,Small,Cash on Delivery,High,Clear,5,No,NaN,1,7.4,Delivered
32356,ORD-032357,2026-03-15,CUS-005675,Consumer,Abu Dhabi,United Arab Emirates,WH-004,Toronto,Sports & Fitness,0.1,...,Small,Debit Card,Low,Cloudy,2,No,NaN,1,43.4,Delivered
32357,ORD-032358,2026-11-24,CUS-005471,Premium,Nantes,France,WH-002,Los Angeles,Fashion,0.1,...,Small,Debit Card,Normal,Cloudy,5,No,NaN,1,21.2,Delivered
32367,ORD-032368,2026-06-20,CUS-004395,Consumer,Madrid,Spain,WH-006,Berlin,Office Supplies,0.1,...,Small,Credit Card,Low,Storm,2,No,NaN,3,11.4,Exception
32385,ORD-032386,2026-07-03,CUS-006221,Consumer,Rome,Italy,WH-001,New York,Automotive,0.1,...,Small,Credit Card,Normal,Clear,3,No,NaN,1,18.5,Delivered

In [76]:
df.sort_values(by='product_weight_kg', ascending=False).head(3)

,order_id,order_date,customer_id,customer_segment,customer_city,customer_country,warehouse_id,warehouse_city,product_category,product_weight_kg,...,package_size,payment_method,order_priority,weather_condition,customer_rating,return_requested,return_reason,delivery_attempts,warehouse_processing_hours,tracking_status
7727,ORD-007728,2026-02-16,CUS-001043,Enterprise,Riyadh,Saudi Arabia,WH-003,Chicago,Automotive,52.19,...,Oversized,Debit Card,High,Snow,4,No,NaN,1,7.2,Delivered
19079,ORD-019080,2026-08-11,CUS-001834,Consumer,Singapore,Singapore,WH-005,London,Automotive,49.65,...,Oversized,Bank Transfer,Normal,Clear,2,No,NaN,1,19.1,Delivered
9120,ORD-009121,2026-08-03,CUS-000924,Consumer,Paris,France,WH-003,Chicago,Automotive,47.18,...,Oversized,PayPal,Urgent,Clear,5,No,NaN,1,7.2,Delivered

In [77]:
df_4 = df.sort_values(by='product_weight_kg', ascending=False).head(3)

In [79]:
df_4.to_csv('../data/processed/top_3_heavy_product.csv')