### Объединение датафреймов
- merge
### Сводная таблица 
- pivot_table

## Задание
- Скачать данные с Gapminder (https://www.gapminder.org/data)
- Предобработать данные:
  - Развернуть данные
  - Преоброзовать типы
  - Убрать Nan
- Объединить данные через merge
- Вычислить новый столбец использую оба показателя
- Сделать сводную таблицу

In [1]:
import pandas as pd

In [2]:
df_pop = pd.read_csv('../data/raw/gapminder/pop.csv')

In [3]:
df_ppl_poverty = pd.read_csv('../data/raw/gapminder/number_of_people_in_poverty.csv')

In [4]:
df_pop

,geo,name,1800,1801,1802,1803,1804,1805,1806,1807,...,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
0,afg,Afghanistan,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3280000,...,124110001.0,124854162.0,125589411.0,126306889.0,126990147.0,127647762.0,128305496.0,128964762.0,129616118.0,130216739.0
1,ago,Angola,1567028,1567028,1567028,1567028,1567028,1567028,1567028,1567028,...,138919849.0,140249378.0,141550054.0,142835147.0,144102524.0,145340832.0,146549586.0,147743369.0,148912810.0,150045574.0
2,alb,Albania,400000,401773,403554,405343,407140,408945,410758,412579,...,1344055.0,1324192.0,1304876.0,1286145.0,1268008.0,1250429.0,1233362.0,1216785.0,1200681.0,1184997.0
3,and,Andorra,2654,2654,2654,2654,2654,2654,2654,2654,...,52781.0,52134.0,51484.0,50843.0,50211.0,49586.0,48973.0,48373.0,47791.0,47222.0
4,are,UAE,40153,40153,40153,40153,40153,40153,40153,40153,...,24075187.0,24298127.0,24521988.0,24747048.0,24973506.0,25201603.0,25431504.0,25663508.0,25897696.0,26134299.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,wsm,Samoa,47300,47292,47284,47276,47268,47260,47252,47244,...,370240.0,371993.0,373663.0,375252.0,376788.0,378279.0,379683.0,381010.0,382317.0,383557.0
191,yem,Yemen,2593000,2593000,2593000,2593000,2593000,2593000,2593000,2593000,...,106510730.0,106998027.0,107459605.0,107895476.0,108308131.0,108699429.0,109068203.0,109414685.0,109738709.0,110035634.0
192,zaf,South Africa,1447911,1453209,1458526,1463862,1469219,1474594,1479989,1485404,...,92399701.0,92635394.0,92860583.0,93085412.0,93300481.0,93502148.0,93695466.0,93893514.0,94101365.0,94314448.0
193,zmb,Zambia,747000,758402,769979,781732,793665,805780,818080,830567,...,61098687.0,61512696.0,61915359.0,62311179.0,62698035.0,63070548.0,63434684.0,63791046.0,64136921.0,64473916.0
194,zwe,Zimbabwe,1085814,1085814,1085814,1085814,1085814,1085814,1085814,1085814,...,36284409.0,36405082.0,36516149.0,36625729.0,36739734.0,36840486.0,36932287.0,37019886.0,37096560.0,37166572.0

In [5]:
df_pop = pd.melt(
    df_pop,
    id_vars=['geo', 'name'],
    var_name='year',
    value_name='population',
)

In [6]:
df_pop

       geo          name  year   population
0      afg   Afghanistan  1800    3280000.0
1      ago        Angola  1800    1567028.0
2      alb       Albania  1800     400000.0
3      and       Andorra  1800       2654.0
4      are           UAE  1800      40153.0
...    ...           ...   ...          ...
58690  wsm         Samoa  2100     383557.0
58691  yem         Yemen  2100  110035634.0
58692  zaf  South Africa  2100   94314448.0
58693  zmb        Zambia  2100   64473916.0
58694  zwe      Zimbabwe  2100   37166572.0

[58695 rows x 4 columns]

In [7]:
df_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58695 entries, 0 to 58694
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   geo         58695 non-null  object
 1   name        58695 non-null  object
 2   year        58695 non-null  object
 3   population  58595 non-null  float64
dtypes: float64(1), object(3)
memory usage: 1.8+ MB

In [8]:
df_pop['year'] = pd.to_numeric(df_pop['year'])

In [9]:
df_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58695 entries, 0 to 58694
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   geo         58695 non-null  object
 1   name        58695 non-null  object
 2   year        58695 non-null  int64
 3   population  58595 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.8+ MB

In [13]:
df_pop[(df_pop['name']=='Russia') & (df_pop['year']==2020)]

       geo    name  year   population
43048  rus  Russia  2020  146371299.0

In [14]:
df_ppl_poverty = pd.melt(
    df_ppl_poverty,
    id_vars=['geo', 'name'],
    var_name='year',
    value_name='people_in_poverty',
)

In [15]:
df_ppl_poverty

       geo          name  year  people_in_poverty
0      afg   Afghanistan  1800          3082964.0
1      ago        Angola  1800          1475262.0
2      alb       Albania  1800           372384.0
3      and       Andorra  1800                NaN
4      are           UAE  1800            18572.0
...    ...           ...   ...                ...
58389  wsm         Samoa  2100              199.0
58390  yem         Yemen  2100          3176913.0
58391  zaf  South Africa  2100          1594438.0
58392  zmb        Zambia  2100          3370040.0
58393  zwe      Zimbabwe  2100           197640.0

[58394 rows x 4 columns]

In [16]:
df_ppl_poverty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58394 entries, 0 to 58393
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   geo                58394 non-null  object
 1   name               58394 non-null  object
 2   year               58394 non-null  object
 3   people_in_poverty  56248 non-null  float64
dtypes: float64(1), object(3)
memory usage: 1.8+ MB

In [18]:
df_ppl_poverty = df_ppl_poverty.dropna(ignore_index=True)

In [19]:
df_ppl_poverty['year'] = pd.to_numeric(df_ppl_poverty['year'])

/tmp/ipykernel_3161/2287007534.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ppl_poverty['year'] = pd.to_numeric(df_ppl_poverty['year'])

In [20]:
df_ppl_poverty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56248 entries, 0 to 56247
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   geo                56248 non-null  object
 1   name               56248 non-null  object
 2   year               56248 non-null  int64
 3   people_in_poverty  56248 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.7+ MB

In [23]:
df_merged = pd.merge(
    left=df_pop,
    right=df_ppl_poverty,
    how='inner',
    left_on=['geo', 'name', 'year'],
    right_on=['geo', 'name', 'year'],
)

In [24]:
df_merged

       geo          name  year   population  people_in_poverty
0      afg   Afghanistan  1800    3280000.0          3082964.0
1      ago        Angola  1800    1567028.0          1475262.0
2      alb       Albania  1800     400000.0           372384.0
3      are           UAE  1800      40153.0            18572.0
4      arg     Argentina  1800     534000.0           288576.0
...    ...           ...   ...          ...                ...
56243  wsm         Samoa  2100     383557.0              199.0
56244  yem         Yemen  2100  110035634.0          3176913.0
56245  zaf  South Africa  2100   94314448.0          1594438.0
56246  zmb        Zambia  2100   64473916.0          3370040.0
56247  zwe      Zimbabwe  2100   37166572.0           197640.0

[56248 rows x 5 columns]

In [25]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56248 entries, 0 to 56247
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   geo                56248 non-null  object
 1   name               56248 non-null  object
 2   year               56248 non-null  int64
 3   population         56248 non-null  float64
 4   people_in_poverty  56248 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 2.1+ MB

In [35]:
df_merged['share_poverty'] = df_merged['people_in_poverty'] / df_merged['population'] * 100

In [36]:
df_merged[df_merged['share_poverty']<0]

Empty DataFrame
Columns: [geo, name, year, population, people_in_poverty, share_poverty]
Index: []

In [37]:
pd.pivot_table(
    df_merged[df_merged['year']>=2000],
    index=['geo', 'name'],
    values=['people_in_poverty', 'share_poverty'],
    aggfunc=['mean', 'min', 'max'],
).sort_values(('mean', 'share_poverty'))

                                          mean                \
                             people_in_poverty share_poverty
geo name
are UAE                           1.646667e+01      0.000089
qat Qatar                         3.093220e+01      0.000514
sgp Singapore                     8.562376e+01      0.001836
and Andorra                       2.000000e+00      0.002628
svn Slovenia                      1.605258e+02      0.008105
...                                        ...           ...
mwi Malawi                        1.308633e+07     45.960512
caf Central African Republic      4.131974e+06     47.435897
moz Mozambique                    2.463586e+07     51.010752
cod Congo, Dem. Rep.              9.717561e+07     56.420268
ssd South Sudan                   1.050915e+07     63.896858

                                           min                \
                             people_in_poverty share_poverty
geo name
are UAE                                    6.0      0.000045
qat Qatar                                  2.0      0.000053
sgp Singapore                              4.0      0.000066
and Andorra                                1.0      0.001192
svn Slovenia                               1.0      0.000048
...                                        ...           ...
mwi Malawi                           2651782.0      4.483811
caf Central African Republic         2364955.0     12.593515
moz Mozambique                       7445245.0      7.135115
cod Congo, Dem. Rep.                47688038.0     12.062635
ssd South Sudan                      3865137.0     27.345012

                                           max
                             people_in_poverty share_poverty
geo name
are UAE                                   31.0      0.000150
qat Qatar                                 82.0      0.001128
sgp Singapore                            799.0      0.019801
and Andorra                                4.0      0.005169
svn Slovenia                            2514.0      0.125894
...                                        ...           ...
mwi Malawi                          19510539.0     75.240159
caf Central African Republic         5524397.0     73.836756
moz Mozambique                      35896954.0     86.850639
cod Congo, Dem. Rep.               135845098.0     95.003483
ssd South Sudan                     13941695.0     89.937400

[192 rows x 6 columns]