## Основы Pandas
- Описание датафрейма
- Чтение и выгрузка данных
- Сортировка

## Задание
- Скачать данные с Kaggle (https://www.kaggle.com/datasets)
- Сортировать данные и некотрый срез (head, tail) сохранить как csv

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('../data/raw/world_population.csv')

In [7]:
df.head(5)

,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00

In [8]:
df.tail()

,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572,11655,12182,13142,14723,13454,11315,9377,142,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986,556048,491824,413296,270375,178529,116775,76371,266000,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20

In [9]:
df.shape

(234, 17)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Rank                         234 non-null    int64
 1   CCA3                         234 non-null    object
 2   Country/Territory            234 non-null    object
 3   Capital                      234 non-null    object
 4   Continent                    234 non-null    object
 5   2022 Population              234 non-null    int64
 6   2020 Population              234 non-null    int64
 7   2015 Population              234 non-null    int64
 8   2010 Population              234 non-null    int64
 9   2000 Population              234 non-null    int64
 10  1990 Population              234 non-null    int64
 11  1980 Population              234 non-null    int64
 12  1970 Population              234 non-null    int64
 13  Area (km²)                   234 non-null    int64
 14  Density (per km²)            234 non-null    float64
 15  Growth Rate                  234 non-null    float64
 16  World Population Percentage  234 non-null    float64
dtypes: float64(3), int64(10), object(4)
memory usage: 31.2+ KB

In [13]:
df.columns

Index(['Rank', 'CCA3', 'Country/Territory', 'Capital', 'Continent',
       '2022 Population', '2020 Population', '2015 Population',
       '2010 Population', '2000 Population', '1990 Population',
       '1980 Population', '1970 Population', 'Area (km²)', 'Density (per km²)',
       'Growth Rate', 'World Population Percentage'],
      dtype='object')

In [14]:
list(df.columns)

['Rank',
 'CCA3',
 'Country/Territory',
 'Capital',
 'Continent',
 '2022 Population',
 '2020 Population',
 '2015 Population',
 '2010 Population',
 '2000 Population',
 '1990 Population',
 '1980 Population',
 '1970 Population',
 'Area (km²)',
 'Density (per km²)',
 'Growth Rate',
 'World Population Percentage']

In [15]:
for column in df.columns:
    print(f'---- {column} ---')

---- Rank ---
---- CCA3 ---
---- Country/Territory ---
---- Capital ---
---- Continent ---
---- 2022 Population ---
---- 2020 Population ---
---- 2015 Population ---
---- 2010 Population ---
---- 2000 Population ---
---- 1990 Population ---
---- 1980 Population ---
---- 1970 Population ---
---- Area (km²) ---
---- Density (per km²) ---
---- Growth Rate ---
---- World Population Percentage ---

In [17]:
df.dtypes

Rank                             int64
CCA3                            object
Country/Territory               object
Capital                         object
Continent                       object
2022 Population                  int64
2020 Population                  int64
2015 Population                  int64
2010 Population                  int64
2000 Population                  int64
1990 Population                  int64
1980 Population                  int64
1970 Population                  int64
Area (km²)                       int64
Density (per km²)              float64
Growth Rate                    float64
World Population Percentage    float64
dtype: object

In [20]:
dict(df.dtypes)

{'Rank': dtype('int64'),
 'CCA3': dtype('O'),
 'Country/Territory': dtype('O'),
 'Capital': dtype('O'),
 'Continent': dtype('O'),
 '2022 Population': dtype('int64'),
 '2020 Population': dtype('int64'),
 '2015 Population': dtype('int64'),
 '2010 Population': dtype('int64'),
 '2000 Population': dtype('int64'),
 '1990 Population': dtype('int64'),
 '1980 Population': dtype('int64'),
 '1970 Population': dtype('int64'),
 'Area (km²)': dtype('int64'),
 'Density (per km²)': dtype('float64'),
 'Growth Rate': dtype('float64'),
 'World Population Percentage': dtype('float64')}

In [19]:
for column, dtype in (df.dtypes).items():
    print(f'столбец: {column} с типом {dtype}')

столбец: Rank с типом int64
столбец: CCA3 с типом object
столбец: Country/Territory с типом object
столбец: Capital с типом object
столбец: Continent с типом object
столбец: 2022 Population с типом int64
столбец: 2020 Population с типом int64
столбец: 2015 Population с типом int64
столбец: 2010 Population с типом int64
столбец: 2000 Population с типом int64
столбец: 1990 Population с типом int64
столбец: 1980 Population с типом int64
столбец: 1970 Population с типом int64
столбец: Area (km²) с типом int64
столбец: Density (per km²) с типом float64
столбец: Growth Rate с типом float64
столбец: World Population Percentage с типом float64

In [22]:
df.describe()

,Rank,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
count,234.000000,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,234.000000,234.000000,234.000000
mean,117.500000,3.407441e+07,3.350107e+07,3.172996e+07,2.984524e+07,2.626947e+07,2.271022e+07,1.898462e+07,1.578691e+07,5.814494e+05,452.127044,1.009577,0.427051
std,67.694165,1.367664e+08,1.355899e+08,1.304050e+08,1.242185e+08,1.116982e+08,9.783217e+07,8.178519e+07,6.779509e+07,1.761841e+06,2066.121904,0.013385,1.714977
min,1.000000,5.100000e+02,5.200000e+02,5.640000e+02,5.960000e+02,6.510000e+02,7.000000e+02,7.330000e+02,7.520000e+02,1.000000e+00,0.026100,0.912000,0.000000
25%,59.250000,4.197385e+05,4.152845e+05,4.046760e+05,3.931490e+05,3.272420e+05,2.641158e+05,2.296142e+05,1.559970e+05,2.650000e+03,38.417875,1.001775,0.010000
50%,117.500000,5.559944e+06,5.493074e+06,5.307400e+06,4.942770e+06,4.292907e+06,3.825410e+06,3.141146e+06,2.604830e+06,8.119950e+04,95.346750,1.007900,0.070000
75%,175.750000,2.247650e+07,2.144798e+07,1.973085e+07,1.915957e+07,1.576230e+07,1.186923e+07,9.826054e+06,8.817329e+06,4.304258e+05,238.933250,1.016950,0.280000
max,234.000000,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,9.823725e+08,8.225344e+08,1.709824e+07,23172.266700,1.069100,17.880000

In [23]:
type(1)

int

In [28]:
type(1.1)

float

In [24]:
type('Hello, world!')

str

In [25]:
type(df)

pandas.core.frame.DataFrame

In [26]:
type(df['2022 Population'])

pandas.core.series.Series

In [27]:
type(df['2022 Population'][0])

numpy.int64

In [29]:
type(df['Density (per km²)'][0])

numpy.float64

In [33]:
df['2022 Population'].head()

0    41128771
1     2842321
2    44903225
3       44273
4       79824
Name: 2022 Population, dtype: int64

In [35]:
df['Country/Territory'].head()

0       Afghanistan
1           Albania
2           Algeria
3    American Samoa
4           Andorra
Name: Country/Territory, dtype: object

In [36]:
df_2 = df.set_index(df['Country/Territory'])

In [39]:
df_2['2022 Population']['Russia']

np.int64(144713314)

In [43]:
df['2022 Population']

0      41128771
1       2842321
2      44903225
3         44273
4         79824
         ...
229       11572
230      575986
231    33696614
232    20017675
233    16320537
Name: 2022 Population, Length: 234, dtype: int64

In [42]:
df_2['2022 Population']

Country/Territory
Afghanistan          41128771
Albania               2842321
Algeria              44903225
American Samoa          44273
Andorra                 79824
                       ...
Wallis and Futuna       11572
Western Sahara         575986
Yemen                33696614
Zambia               20017675
Zimbabwe             16320537
Name: 2022 Population, Length: 234, dtype: int64

In [45]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 234 entries, Afghanistan to Zimbabwe
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Rank                         234 non-null    int64
 1   CCA3                         234 non-null    object
 2   Country/Territory            234 non-null    object
 3   Capital                      234 non-null    object
 4   Continent                    234 non-null    object
 5   2022 Population              234 non-null    int64
 6   2020 Population              234 non-null    int64
 7   2015 Population              234 non-null    int64
 8   2010 Population              234 non-null    int64
 9   2000 Population              234 non-null    int64
 10  1990 Population              234 non-null    int64
 11  1980 Population              234 non-null    int64
 12  1970 Population              234 non-null    int64
 13  Area (km²)                   234 non-null    int64
 14  Density (per km²)            234 non-null    float64
 15  Growth Rate                  234 non-null    float64
 16  World Population Percentage  234 non-null    float64
dtypes: float64(3), int64(10), object(4)
memory usage: 41.0+ KB

In [49]:
df['Density (per km²)']

0       63.0587
1       98.8702
2       18.8531
3      222.4774
4      170.5641
         ...
229     81.4930
230      2.1654
231     63.8232
232     26.5976
233     41.7665
Name: Density (per km²), Length: 234, dtype: float64

In [53]:
type(df['Density (per km²)'])

pandas.core.series.Series

In [54]:
df[['Density (per km²)', 'CCA3']].head()

   Density (per km²) CCA3
0            63.0587  AFG
1            98.8702  ALB
2            18.8531  DZA
3           222.4774  ASM
4           170.5641  AND

In [58]:
df[['Density (per km²)']]

     Density (per km²)
0              63.0587
1              98.8702
2              18.8531
3             222.4774
4             170.5641
..                 ...
229            81.4930
230             2.1654
231            63.8232
232            26.5976
233            41.7665

[234 rows x 1 columns]

In [57]:
type(df[['Density (per km²)']])

pandas.core.frame.DataFrame

In [64]:
df_3 = df.sort_values('2022 Population', ascending=False).head(10)

In [65]:
df_3

,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
41,1,CHN,China,Beijing,Asia,1425887337,1424929781,1393715448,1348191368,1264099069,1153704252,982372466,822534450,9706961,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1417173173,1396387127,1322866505,1240613620,1059633675,870452165,696828385,557501301,3287590,431.0675,1.0068,17.77
221,3,USA,United States,"Washington, D.C.",North America,338289857,335942003,324607776,311182845,282398554,248083732,223140018,200328340,9372610,36.0935,1.0038,4.24
93,4,IDN,Indonesia,Jakarta,Asia,275501339,271857970,259091970,244016173,214072421,182159874,148177096,115228394,1904569,144.6529,1.0064,3.45
156,5,PAK,Pakistan,Islamabad,Asia,235824862,227196741,210969298,194454498,154369924,115414069,80624057,59290872,881912,267.4018,1.0191,2.96
149,6,NGA,Nigeria,Abuja,Africa,218541212,208327405,183995785,160952853,122851984,95214257,72951439,55569264,923768,236.5759,1.0241,2.74
27,7,BRA,Brazil,Brasilia,South America,215313498,213196304,205188205,196353492,175873720,150706446,122288383,96369875,8515767,25.2841,1.0046,2.70
16,8,BGD,Bangladesh,Dhaka,Asia,171186372,167420951,157830000,148391139,129193327,107147651,83929765,67541860,147570,1160.0350,1.0108,2.15
171,9,RUS,Russia,Moscow,Europe,144713314,145617329,144668389,143242599,146844839,148005704,138257420,130093010,17098242,8.4636,0.9973,1.81
131,10,MEX,Mexico,Mexico City,North America,127504125,125998302,120149897,112532401,97873442,81720428,67705186,50289306,1964375,64.9082,1.0063,1.60

In [66]:
df_3.to_csv('../data/processed/word_pop_top_10.csv')