### Разворачивание данных
- melt
### Преоброзование типов
- pd.to_numeric
- pd.to_datetime
- astype
### Работа с Nan
- fillna
- dropna
### Группировка
- groupby

## Задание
- Скачать данные с Gapminder (https://www.gapminder.org/data)
- Развернуть данные
- Преоброзовать типы
- Убрать Nan
- Сделать датафрейм с группировкой

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../data/raw/tax_revenue_percent_of_gdp.csv')

In [5]:
df.head()

,geo,name,1972,1973,1974,1975,1976,1977,1978,1979,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,afg,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.58538,9.50265,9.89845,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ago,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.70951,8.57579,8.05554,9.92888,11.28885,20.51761,10.70333,12.73181,8.86913,7.74436
2,alb,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.38129,17.40320,18.54766,18.27695,17.93099,16.89554,18.09623,18.06078,17.80216,18.01529
3,and,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,14.30017,13.93435,12.17152,12.85298,13.61962,14.09633,15.58631
4,are,UAE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.05413,0.04068,0.06353,0.05684,0.93653,0.66740,0.52604,0.56870,0.61667,0.64752

In [27]:
df_melt = pd.melt(
    df,
    id_vars=['geo', 'name'],
    var_name='year',
    value_name='tax_revenue_percent_of_gdp'
)

In [8]:
df_melt

      geo          name  year  tax_revenue_percent_of_gdp
0     afg   Afghanistan  1972                         NaN
1     ago        Angola  1972                         NaN
2     alb       Albania  1972                         NaN
3     and       Andorra  1972                         NaN
4     are           UAE  1972                         NaN
...   ...           ...   ...                         ...
8475  vut       Vanuatu  2024                         NaN
8476  wsm         Samoa  2024                         NaN
8477  zaf  South Africa  2024                         NaN
8478  zmb        Zambia  2024                         NaN
8479  zwe      Zimbabwe  2024                         NaN

[8480 rows x 4 columns]

In [9]:
df_melt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8480 entries, 0 to 8479
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   geo                         8480 non-null   object
 1   name                        8480 non-null   object
 2   year                        8480 non-null   object
 3   tax_revenue_percent_of_gdp  4658 non-null   float64
dtypes: float64(1), object(3)
memory usage: 265.1+ KB

In [10]:
df_melt.notna()

       geo  name  year  tax_revenue_percent_of_gdp
0     True  True  True                       False
1     True  True  True                       False
2     True  True  True                       False
3     True  True  True                       False
4     True  True  True                       False
...    ...   ...   ...                         ...
8475  True  True  True                       False
8476  True  True  True                       False
8477  True  True  True                       False
8478  True  True  True                       False
8479  True  True  True                       False

[8480 rows x 4 columns]

In [11]:
df_melt.isna()

        geo   name   year  tax_revenue_percent_of_gdp
0     False  False  False                        True
1     False  False  False                        True
2     False  False  False                        True
3     False  False  False                        True
4     False  False  False                        True
...     ...    ...    ...                         ...
8475  False  False  False                        True
8476  False  False  False                        True
8477  False  False  False                        True
8478  False  False  False                        True
8479  False  False  False                        True

[8480 rows x 4 columns]

In [12]:
df_melt.isna().sum()

geo                              0
name                             0
year                             0
tax_revenue_percent_of_gdp    3822
dtype: int64

In [23]:
df_melt['tax_revenue_percent_of_gdp'] = df_melt['tax_revenue_percent_of_gdp'].fillna(0)

In [26]:
df_melt = df_melt.fillna(0)

In [46]:
df_clean = df_melt.dropna(
    # axis=0,  # 0, 1
    # how='any',  # any, all
    # thresh=4,
    # subset='tax_revenue_percent_of_gdp',
    # subset=['geo', 'name', 'tax_revenue_percent_of_gdp'],
    # ignore_index=True
)

In [50]:
df_clean = df_clean.reset_index(drop=True)

In [51]:
df_clean

      geo         name  year  tax_revenue_percent_of_gdp
0     aus    Australia  1972                    17.81543
1     aut      Austria  1972                    17.95913
2     che  Switzerland  1972                     6.79437
3     chl        Chile  1972                    15.92242
4     cri   Costa Rica  1972                    11.44137
...   ...          ...   ...                         ...
4653  tza     Tanzania  2024                    12.80291
4654  uga       Uganda  2024                    12.62556
4655  ukr      Ukraine  2024                    21.02797
4656  ury      Uruguay  2024                    18.16236
4657  usa          USA  2024                    10.97439

[4658 rows x 4 columns]

In [53]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4658 entries, 0 to 4657
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   geo                         4658 non-null   object
 1   name                        4658 non-null   object
 2   year                        4658 non-null   object
 3   tax_revenue_percent_of_gdp  4658 non-null   float64
dtypes: float64(1), object(3)
memory usage: 145.7+ KB

In [61]:
pd.to_numeric(
    df_clean['year'],
    downcast='integer'
)

0       1972
1       1972
2       1972
3       1972
4       1972
        ...
4653    2024
4654    2024
4655    2024
4656    2024
4657    2024
Name: year, Length: 4658, dtype: int16

In [62]:
df_clean['year'] = pd.to_numeric(df_clean['year'])

In [63]:
df_clean

      geo         name  year  tax_revenue_percent_of_gdp
0     aus    Australia  1972                    17.81543
1     aut      Austria  1972                    17.95913
2     che  Switzerland  1972                     6.79437
3     chl        Chile  1972                    15.92242
4     cri   Costa Rica  1972                    11.44137
...   ...          ...   ...                         ...
4653  tza     Tanzania  2024                    12.80291
4654  uga       Uganda  2024                    12.62556
4655  ukr      Ukraine  2024                    21.02797
4656  ury      Uruguay  2024                    18.16236
4657  usa          USA  2024                    10.97439

[4658 rows x 4 columns]

In [64]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4658 entries, 0 to 4657
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   geo                         4658 non-null   object
 1   name                        4658 non-null   object
 2   year                        4658 non-null   int64
 3   tax_revenue_percent_of_gdp  4658 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 145.7+ KB

In [67]:
df_clean.groupby(by=['geo', 'name']).agg('mean')

                         year  tax_revenue_percent_of_gdp
geo name
afg Afghanistan   2011.500000                    7.800539
ago Angola        2011.500000                   14.914650
alb Albania       2011.428571                   16.357564
and Andorra       2021.000000                   13.794469
are UAE           2014.058824                    0.512437
...                       ...                         ...
vut Vanuatu       2010.238095                   17.190969
wsm Samoa         2017.500000                   23.429215
zaf South Africa  1997.500000                   21.127247
zmb Zambia        2005.677419                   15.502947
zwe Zimbabwe      2013.500000                   13.525979

[160 rows x 2 columns]

In [69]:
df_clean[['name', 'tax_revenue_percent_of_gdp']].groupby(by='name').agg('mean')

             tax_revenue_percent_of_gdp
name
Afghanistan                    7.800539
Albania                       16.357564
Andorra                       13.794469
Angola                        14.914650
Argentina                     10.446823
...                                 ...
Uruguay                       16.651926
Uzbekistan                    12.650125
Vanuatu                       17.190969
Zambia                        15.502947
Zimbabwe                      13.525979

[160 rows x 1 columns]

In [70]:
df_clean[['name', 'tax_revenue_percent_of_gdp']].groupby(by='name').agg('mean').sort_values(by='tax_revenue_percent_of_gdp')

              tax_revenue_percent_of_gdp
name
UAE                             0.512437
Iraq                            1.721568
Somalia                         1.946174
Bahrain                         2.748943
Saudi Arabia                    5.069017
...                                  ...
Nauru                          30.024740
Denmark                        31.302315
Lesotho                        31.740868
Timor-Leste                    55.297885
Sudan                         131.271167

[160 rows x 1 columns]

In [72]:
df_grp = df_clean[['name', 'tax_revenue_percent_of_gdp']].groupby(by='name').agg(['mean', 'median', 'min', 'max', 'count'])

In [75]:
df_grp

            tax_revenue_percent_of_gdp
                                  mean     median       min       max count
name
Afghanistan                   7.800539   7.646590   5.28346   9.89845    12
Albania                      16.357564  17.587930   8.76625  18.54766    21
Andorra                      13.794469  13.934350  12.17152  15.58631     7
Angola                       14.914650  14.026675   7.74436  29.24668    26
Argentina                    10.446823  10.708120   4.83851  13.31785    35
...                                ...        ...       ...       ...   ...
Uruguay                      16.651926  16.982840  10.44732  21.73225    53
Uzbekistan                   12.650125  13.174410  10.36875  13.80048    13
Vanuatu                      17.190969  17.381920  14.04026  20.18514    21
Zambia                       15.502947  15.440010  11.68752  19.48288    31
Zimbabwe                     13.525979  16.446640   5.46550  17.92841     8

[160 rows x 5 columns]

In [77]:
df_grp.sort_values(by=('tax_revenue_percent_of_gdp', 'median'))

            tax_revenue_percent_of_gdp
                                  mean    median       min       max count
name
UAE                           0.512437   0.52604   0.04068   1.12245    17
Iraq                          1.721568   1.66430   0.91477   2.68703     6
Somalia                       1.946174   1.93574   1.61766   2.27753     8
Kuwait                        6.194052   1.93800   0.08581  37.43169    25
Bahrain                       2.748943   2.87819   0.79238   4.98152    31
...                                ...       ...       ...       ...   ...
Namibia                      28.079582  27.67182  23.01056  34.62869    34
New Zealand                  28.683370  28.55763  24.46646  33.24646    41
Nauru                        30.024740  28.84380  16.97848  44.34683    11
Lesotho                      31.740868  31.17043  22.93956  40.22476    42
Denmark                      31.302315  31.73557  26.52883  36.58507    53

[160 rows x 5 columns]