### Разворачивание данных
- melt
### Преоброзование типов
- pd.to_numeric
- pd.to_datetime
### Работа с Nan
- fillna
- dropna
### Группировка
- groupby

## Задание
- Скачать данные с Gapminder (https://www.gapminder.org/data)
- Развернуть данные
- Преоброзовать типы
- Убрать Nan
- Сделать датафрейм с группировкой

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/raw/inflation_annual_percent.csv')

In [3]:
df.head()

,geo,name,1961,1962,1963,1964,1965,1966,1967,1968,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,afg,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.44756,-2.19753,2.40366,2.07135,6.52148,6.96295,2.83900,9.40624,2.92366,NaN
1,ago,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-2.95735,20.87270,23.71281,25.19416,19.86589,16.06358,35.65369,18.12177,17.92923,24.60458
2,alb,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.77158,-0.86427,2.72507,1.45329,1.00063,0.04106,3.44426,9.86161,5.73391,2.35318
3,and,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.66059,0.34780,1.13651,1.01248,1.37475,1.11379,2.55886,4.23665,6.29560,3.14366
4,are,UAE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-16.05983,-5.41837,6.80480,7.56771,-2.74227,-9.85385,13.12687,12.59787,-2.02055,1.62665

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 66 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   geo     193 non-null    object
 1   name    193 non-null    object
 2   1961    104 non-null    float64
 3   1962    108 non-null    float64
 4   1963    108 non-null    float64
 5   1964    108 non-null    float64
 6   1965    108 non-null    float64
 7   1966    109 non-null    float64
 8   1967    112 non-null    float64
 9   1968    113 non-null    float64
 10  1969    113 non-null    float64
 11  1970    113 non-null    float64
 12  1971    134 non-null    float64
 13  1972    134 non-null    float64
 14  1973    135 non-null    float64
 15  1974    135 non-null    float64
 16  1975    136 non-null    float64
 17  1976    138 non-null    float64
 18  1977    139 non-null    float64
 19  1978    143 non-null    float64
 20  1979    143 non-null    float64
 21  1980    144 non-null    float64
 22  1981    154 non-null    float64
 23  1982    155 non-null    float64
 24  1983    157 non-null    float64
 25  1984    157 non-null    float64
 26  1985    158 non-null    float64
 27  1986    160 non-null    float64
 28  1987    160 non-null    float64
 29  1988    164 non-null    float64
 30  1989    164 non-null    float64
 31  1990    166 non-null    float64
 32  1991    184 non-null    float64
 33  1992    185 non-null    float64
 34  1993    186 non-null    float64
 35  1994    186 non-null    float64
 36  1995    187 non-null    float64
 37  1996    188 non-null    float64
 38  1997    188 non-null    float64
 39  1998    190 non-null    float64
 40  1999    190 non-null    float64
 41  2000    190 non-null    float64
 42  2001    191 non-null    float64
 43  2002    191 non-null    float64
 44  2003    191 non-null    float64
 45  2004    191 non-null    float64
 46  2005    191 non-null    float64
 47  2006    191 non-null    float64
 48  2007    191 non-null    float64
 49  2008    191 non-null    float64
 50  2009    192 non-null    float64
 51  2010    191 non-null    float64
 52  2011    191 non-null    float64
 53  2012    190 non-null    float64
 54  2013    190 non-null    float64
 55  2014    191 non-null    float64
 56  2015    191 non-null    float64
 57  2016    190 non-null    float64
 58  2017    190 non-null    float64
 59  2018    190 non-null    float64
 60  2019    189 non-null    float64
 61  2020    189 non-null    float64
 62  2021    189 non-null    float64
 63  2022    189 non-null    float64
 64  2023    188 non-null    float64
 65  2024    181 non-null    float64
dtypes: float64(64), object(2)
memory usage: 99.6+ KB

In [6]:
df_melt = pd.melt(
    df,
    id_vars=['geo', 'name'],
    var_name='year',
    value_name='inflation_annual_percent',
)

In [7]:
df_melt.head()

   geo         name  year  inflation_annual_percent
0  afg  Afghanistan  1961                       NaN
1  ago       Angola  1961                       NaN
2  alb      Albania  1961                       NaN
3  and      Andorra  1961                       NaN
4  are          UAE  1961                       NaN

In [9]:
df_melt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12352 entries, 0 to 12351
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   geo                       12352 non-null  object
 1   name                      12352 non-null  object
 2   year                      12352 non-null  object
 3   inflation_annual_percent  10505 non-null  float64
dtypes: float64(1), object(3)
memory usage: 386.1+ KB

In [10]:
df_1 = df_melt.copy()

In [12]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12352 entries, 0 to 12351
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   geo                       12352 non-null  object
 1   name                      12352 non-null  object
 2   year                      12352 non-null  object
 3   inflation_annual_percent  10505 non-null  float64
dtypes: float64(1), object(3)
memory usage: 386.1+ KB

In [13]:
df_1

       geo          name  year  inflation_annual_percent
0      afg   Afghanistan  1961                       NaN
1      ago        Angola  1961                       NaN
2      alb       Albania  1961                       NaN
3      and       Andorra  1961                       NaN
4      are           UAE  1961                       NaN
...    ...           ...   ...                       ...
12347  wsm         Samoa  2024                   8.42503
12348  yem         Yemen  2024                       NaN
12349  zaf  South Africa  2024                   3.91692
12350  zmb        Zambia  2024                  14.41066
12351  zwe      Zimbabwe  2024                1097.24667

[12352 rows x 4 columns]

In [15]:
df_1['inflation_annual_percent'] = df_1['inflation_annual_percent'].fillna(0)

In [17]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12352 entries, 0 to 12351
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   geo                       12352 non-null  object
 1   name                      12352 non-null  object
 2   year                      12352 non-null  object
 3   inflation_annual_percent  12352 non-null  float64
dtypes: float64(1), object(3)
memory usage: 386.1+ KB

In [18]:
df_1.head()

   geo         name  year  inflation_annual_percent
0  afg  Afghanistan  1961                       0.0
1  ago       Angola  1961                       0.0
2  alb      Albania  1961                       0.0
3  and      Andorra  1961                       0.0
4  are          UAE  1961                       0.0

In [19]:
df_2 = df_melt.copy()

In [22]:
df_2.notna()

        geo  name  year  inflation_annual_percent
0      True  True  True                     False
1      True  True  True                     False
2      True  True  True                     False
3      True  True  True                     False
4      True  True  True                     False
...     ...   ...   ...                       ...
12347  True  True  True                      True
12348  True  True  True                     False
12349  True  True  True                      True
12350  True  True  True                      True
12351  True  True  True                      True

[12352 rows x 4 columns]

In [29]:
df_2.isna().sum()

geo                            0
name                           0
year                           0
inflation_annual_percent    1847
dtype: int64

In [54]:
df_2 = df_2.dropna(
    axis=0,  # 0, 1
    how='any',  # any, all
    # thresh=4,
    subset='inflation_annual_percent',
    # subset=['geo', 'name', 'inflation_annual_percent'],
    # ignore_index=True
)

In [55]:
df_2

       geo          name  year  inflation_annual_percent
5      arg     Argentina  1961                  20.31070
8      aus     Australia  1961                   3.22084
9      aut       Austria  1961                   5.08715
11     bdi       Burundi  1961                  20.07744
12     bel       Belgium  1961                   1.31547
...    ...           ...   ...                       ...
12346  vut       Vanuatu  2024                  -0.70084
12347  wsm         Samoa  2024                   8.42503
12349  zaf  South Africa  2024                   3.91692
12350  zmb        Zambia  2024                  14.41066
12351  zwe      Zimbabwe  2024                1097.24667

[10505 rows x 4 columns]

In [56]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10505 entries, 5 to 12351
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   geo                       10505 non-null  object
 1   name                      10505 non-null  object
 2   year                      10505 non-null  object
 3   inflation_annual_percent  10505 non-null  float64
dtypes: float64(1), object(3)
memory usage: 410.4+ KB

In [57]:
df_2.isna().sum()

geo                         0
name                        0
year                        0
inflation_annual_percent    0
dtype: int64

In [60]:
pd.to_numeric

<function pandas.core.tools.numeric.to_numeric(arg, errors: 'DateTimeErrorChoices' = 'raise', downcast: "Literal['integer', 'signed', 'unsigned', 'float'] | None" = None, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>)>

In [59]:
pd.to_datetime

<function pandas.core.tools.datetimes.to_datetime(arg: 'DatetimeScalarOrArrayConvertible | DictConvertible', errors: 'DateTimeErrorChoices' = 'raise', dayfirst: 'bool' = False, yearfirst: 'bool' = False, utc: 'bool' = False, format: 'str | None' = None, exact: 'bool | lib.NoDefault' = <no_default>, unit: 'str | None' = None, infer_datetime_format: 'lib.NoDefault | bool' = <no_default>, origin: 'str' = 'unix', cache: 'bool' = True) -> 'DatetimeIndex | Series | DatetimeScalar | NaTType | None'>

In [63]:
df_2['year']

5        1961
8        1961
9        1961
11       1961
12       1961
         ...
12346    2024
12347    2024
12349    2024
12350    2024
12351    2024
Name: year, Length: 10505, dtype: object

In [79]:
df_2

       geo          name  year  inflation_annual_percent
5      arg     Argentina  1961                  20.31070
8      aus     Australia  1961                   3.22084
9      aut       Austria  1961                   5.08715
11     bdi       Burundi  1961                  20.07744
12     bel       Belgium  1961                   1.31547
...    ...           ...   ...                       ...
12346  vut       Vanuatu  2024                  -0.70084
12347  wsm         Samoa  2024                   8.42503
12349  zaf  South Africa  2024                   3.91692
12350  zmb        Zambia  2024                  14.41066
12351  zwe      Zimbabwe  2024                1097.24667

[10505 rows x 4 columns]

In [84]:
df_2 = df_2.reset_index(drop=True)

In [85]:
df_2

       geo          name  year  inflation_annual_percent
0      arg     Argentina  1961                  20.31070
1      aus     Australia  1961                   3.22084
2      aut       Austria  1961                   5.08715
3      bdi       Burundi  1961                  20.07744
4      bel       Belgium  1961                   1.31547
...    ...           ...   ...                       ...
10500  vut       Vanuatu  2024                  -0.70084
10501  wsm         Samoa  2024                   8.42503
10502  zaf  South Africa  2024                   3.91692
10503  zmb        Zambia  2024                  14.41066
10504  zwe      Zimbabwe  2024                1097.24667

[10505 rows x 4 columns]

In [86]:
df_2['year'] = pd.to_numeric(
    df_2['year'],
    # downcast='integer'
    # errors='raise',
    # errors='coerce',
)

In [88]:
df_2

       geo          name  year  inflation_annual_percent
0      arg     Argentina  1961                  20.31070
1      aus     Australia  1961                   3.22084
2      aut       Austria  1961                   5.08715
3      bdi       Burundi  1961                  20.07744
4      bel       Belgium  1961                   1.31547
...    ...           ...   ...                       ...
10500  vut       Vanuatu  2024                  -0.70084
10501  wsm         Samoa  2024                   8.42503
10502  zaf  South Africa  2024                   3.91692
10503  zmb        Zambia  2024                  14.41066
10504  zwe      Zimbabwe  2024                1097.24667

[10505 rows x 4 columns]

In [93]:
df_2[['name', 'inflation_annual_percent']].groupby(by='name').agg('mean')

                  inflation_annual_percent
name
Djibouti                          0.984662
San Marino                        1.759077
Switzerland                       2.495013
Japan                             2.500974
Singapore                         2.597455
...                                    ...
Angola                          285.418153
Georgia                         363.943987
Nicaragua                       460.751912
Congo, Dem. Rep.                636.994285
Venezuela                      3971.008519

[193 rows x 1 columns]

In [100]:
df_grp = df_2[['name', 'inflation_annual_percent']].groupby(by='name').agg(['mean', 'median', 'min', 'max', 'count'])

In [101]:
df_grp

            inflation_annual_percent
                                mean     median       min           max count
name
Afghanistan                 5.405594   4.822790 -11.77454      22.52776    23
Albania                    13.004031   2.704920  -2.41730     232.98466    44
Algeria                    10.013078   8.008405  -7.37375      53.78860    64
Andorra                     6.610865   4.058255  -0.08402      28.74155    54
Angola                    285.418153  20.872700 -14.27128    4800.53164    43
...                              ...        ...       ...           ...   ...
Venezuela                3971.008519  27.109975  -0.77574  225690.05992    64
Vietnam                    42.773487   8.433310  -1.71651     411.04025    39
Yemen                      15.777017  13.850985  -8.70527      46.47625    28
Zambia                     24.010820  14.180785 -14.16990     165.53395    64
Zimbabwe                   56.646966   3.706410 -27.04919    1097.24667    64

[193 rows x 5 columns]

In [105]:
df_grp.sort_values(by=('inflation_annual_percent', 'median'))

                 inflation_annual_percent                                     \
                                     mean     median       min           max
name
Djibouti                         0.984662   0.580720  -0.44194       3.35375
Brunei                           3.181808   0.958050 -37.07986      94.77247
Japan                            2.500974   1.345115  -1.88074      20.81005
Cape Verde                       3.614460   1.829365 -29.17246      49.35409
San Marino                       1.759077   1.834475  -1.97239       7.35543
...                                   ...        ...       ...           ...
Sudan                           38.406307  22.910500  -2.39468     243.90725
Uruguay                         36.142065  23.165225   0.67787     191.57412
Venezuela                     3971.008519  27.109975  -0.77574  225690.05992
Congo, Dem. Rep.               636.994285  28.433780  -2.83695   26765.85825
Argentina                      161.248601  28.945050  -3.56110    3046.09115


                 count
name
Djibouti            11
Brunei              50
Japan               64
Cape Verde          44
San Marino          26
...                ...
Sudan               64
Uruguay             64
Venezuela           64
Congo, Dem. Rep.    64
Argentina           64

[193 rows x 5 columns]

In [107]:
df_grp.loc['Russia']

inflation_annual_percent  mean        98.335275
                          median      15.661910
                          min          0.898250
                          max       1490.418420
                          count       35.000000
Name: Russia, dtype: float64