## Работа с текстом
Векторные методы через *str*:
- lower, upper
- strip, lstrip, rstrip
- replace
- contains
- split
- extract

### Данные с https://store.poidata.xyz/
### Задача:
1. Столбец _prov_ привести в порядок 
    - нижний регистр
    - без лишних пробелов
    - без типов субъекта (убрать область, республика и т.д.)
2. Столбец _email_ вытащить домен верхнего уровня (ru, com, org, ...)

In [5]:
import pandas as pd
import numpy as np

In [6]:
df_raw = pd.read_csv('../data/raw/ru_sample.csv')

In [7]:
df_raw

,unique_id,poi_name,brand,poi_tel,super_category,main_category,second_category,all_categories,location_id,area_id,...,postal,country,formatted_address,source_url,email,opening_hours,crawl_time,alternate_names,top_poi_score,top_source_urls
0,6754848,Le Kebab,NaN,+7 950 766 66 69,Restaurants,Syrian restaurant,Fast food restaurant,Fast food joint | Fast food restaurant | Leban...,8463276220664,712314,...,394036.0,Russian Federation,"Prospekt Revolyutsii, 54, Voronezh, Voronezh O...",NaN,NaN,"{'Su':null,'Tu':null,'We':null,'Fr':null,'Th':...",2025-11-05 19:38:08,NaN,0.978743,https://2gis.ru/voronezh/firm/7000000102383595...
1,6754846,Pochta V Sizo,NaN,+7 924 251 88 38,Advertising Services,Mailing service,NaN,Mailing service,8039580463063,676653,...,690106.0,Russian Federation,"Partizanskiy Prospekt, 24, Vladivostok, Primor...",NaN,NaN,"{'Su':[{'open':'09:00','close':'16:30'}],'Tu':...",2025-11-05 19:41:47,NaN,0.907095,https://xn--80aairafa0aom4a.xn--p1ai/ |
2,6754845,Post of Russia,Почта России,+7 800 200 58 88,Advertising Services,Mailing service,NaN,Mailing service,8275012377254,696469,...,450017.0,Russian Federation,"Ulitsa Irendyk, 4, Ufa, Republic of Bashkortos...",NaN,NaN,"{'Su':null,'Tu':[{'open':'08:00','close':'13:0...",2025-11-05 19:42:03,NaN,0.880349,https://www.russianpost.ru/ |
3,6754842,Codes of Russia,Почта России,+7 800 200 58 88,Advertising Services,Mailing service,Post office,Mailing service | Post Office,8483319931344,714001,...,410056.0,Russian Federation,"Codes of Russia, Bakhmet'yevskaya Ulitsa, 33, ...",http://www.pochta.ru,NaN,"{'Su':null,'Tu':[{'open':'09:00','close':'19:0...",2026-08-16 05:58:32,"Post of Russia,0.827586206896552 | Post Codes:...",0.897708,https://ourpostalcode.com/russia-postal-codes/...
4,6754839,City and Malls PFM,NaN,+7 495 803 33 03,Facilities Services,Property administration service,Property maintenance,Asset Management | Building Maintenance | Prop...,8510991262879,716330,...,115280.0,Russian Federation,"Ulitsa Leninskaya Sloboda, 19 строение 6, Mosc...",NaN,NaN,"{'Su':null,'Tu':[{'open':'09:30','close':'18:0...",2025-11-05 19:52:40,NaN,0.943275,https://www.cmpfm.ru/ |
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1910,6385075,OZON,Ozon,+7 495 232 10 00,Retail,E-commerce service,NaN,E-commerce Platform | E-commerce Service | Onl...,8274970915282,696465,...,453400.0,Russian Federation,"Ulitsa Krasnaya Ploshchad', 7, Davlekanovo, Re...",http://www.ozon.ru,NaN,"{'Su':[{'open':'09:00','close':'21:00'}],'Tu':...",2026-08-28 18:51:23,NaN,0.877570,https://www.ozon.ru/geo/tbilisi/ | https://cor...
1911,6385074,Davlekanovo,NaN,+7 987 583 43 55,Broadcast Media Production and Distribution,TV station,Television station,TV network | TV station | Television channel |...,8274970593119,696465,...,453400.0,Russian Federation,"Ulitsa Krasnaya Ploshchad', 11, Davlekanovo, R...",NaN,NaN,"{'Su':null,'Tu':[{'open':'09:00','close':'18:0...",2026-09-03 04:22:21,"Davlekanovsky,0.135911211874499",0.919013,https://en.wikipedia.org/wiki/Davlekanovo | ht...
1912,6385073,Пенсионный фонд,NaN,+7 347 683 21 75,IT Services and IT Consulting,Corporate office,Corporate Office,Business Office | Company Office | Corporate O...,8274970592502,696465,...,453400.0,Russian Federation,"Пенсионный фонд, Ulitsa Pobedy, 4, Davlekanovo...",NaN,NaN,"{'Su':null,'Tu':[{'open':'09:00','close':'18:0...",2026-08-16 21:30:40,"Pensionnyy Fond,0.0666666666666667 | Pension F...",0.825781,https://ru.wikipedia.org/wiki/%D0%9F%D0%B5%D0%...
1913,6385072,Hair Club Men,NaN,+7 927 967 05 36,Individual and Family Services,Barber Shop,Barber shop,Barber Shop | Barber Supply,8274970915043,696465,...,453400.0,Russian Federation,"Hair Club Men, Ulitsa Pobedy, 17, Davlekanovo,...",NaN,NaN,"{'Su':[{'open':'00:00','close':'08:00'},{'open...",2026-09-03 06:39:28,"Hair club men,0.846153846153846 | Hair Club Fo...",0.716781,https://www.walmart.com/c/kp/hair-club-men | h...
1914,6385064,Fabrichnyy,NaN,+7 347 683 17 77,Retail,Shopping mall,NaN,Business Park | Commercial Development | Retai...,8274970593465,696465,...,453400.0,Russian Federation,"Ulitsa Mazhita Gafuri, 4, Davlekanovo, Republi...",NaN,NaN,"{'Su':[{'open':'09:00','close':'18:00'}],'Tu':...",2026-08-23 00:58:27,"Fabrichny,0.260197647316131",0.937881,https://www.trip.com/travel-guide/shops/davlek...

In [8]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1915 entries, 0 to 1914
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   unique_id          1915 non-null   int64
 1   poi_name           1915 non-null   object
 2   brand              160 non-null    object
 3   poi_tel            1915 non-null   object
 4   super_category     1915 non-null   object
 5   main_category      1915 non-null   object
 6   second_category    1345 non-null   object
 7   all_categories     1915 non-null   object
 8   location_id        1915 non-null   int64
 9   area_id            1915 non-null   int64
 10  small_area_id      1915 non-null   int64
 11  latitude           1915 non-null   float64
 12  longitude          1915 non-null   float64
 13  adr                1908 non-null   object
 14  city               1915 non-null   object
 15  neighborhood       1129 non-null   object
 16  prov               1915 non-null   object
 17  postal             1914 non-null   float64
 18  country            1915 non-null   object
 19  formatted_address  1915 non-null   object
 20  source_url         121 non-null    object
 21  email              32 non-null     object
 22  opening_hours      1915 non-null   object
 23  crawl_time         1915 non-null   object
 24  alternate_names    1212 non-null   object
 25  top_poi_score      1915 non-null   float64
 26  top_source_urls    1915 non-null   object
dtypes: float64(4), int64(4), object(19)
memory usage: 404.1+ KB

In [75]:
df = df_raw[['city', 'email', 'all_categories', 'poi_tel']].copy()

In [76]:
df

,city,email,all_categories,poi_tel
0,Voronezh,NaN,Fast food joint | Fast food restaurant | Leban...,+7 950 766 66 69
1,Vladivostok,NaN,Mailing service,+7 924 251 88 38
2,Ufa,NaN,Mailing service,+7 800 200 58 88
3,Saratov,NaN,Mailing service | Post Office,+7 800 200 58 88
4,Москва,NaN,Asset Management | Building Maintenance | Prop...,+7 495 803 33 03
...,...,...,...,...
1910,Davlekanovo,NaN,E-commerce Platform | E-commerce Service | Onl...,+7 495 232 10 00
1911,Davlekanovo,NaN,TV network | TV station | Television channel |...,+7 987 583 43 55
1912,Davlekanovo,NaN,Business Office | Company Office | Corporate O...,+7 347 683 21 75
1913,Davlekanovo,NaN,Barber Shop | Barber Supply,+7 927 967 05 36
1914,Davlekanovo,NaN,Business Park | Commercial Development | Retai...,+7 347 683 17 77

In [77]:
df['city'].str.lower()

0          voronezh
1       vladivostok
2               ufa
3           saratov
4            москва
           ...
1910    davlekanovo
1911    davlekanovo
1912    davlekanovo
1913    davlekanovo
1914    davlekanovo
Name: city, Length: 1915, dtype: object

In [78]:
df['city'].str.upper()

0          VORONEZH
1       VLADIVOSTOK
2               UFA
3           SARATOV
4            МОСКВА
           ...
1910    DAVLEKANOVO
1911    DAVLEKANOVO
1912    DAVLEKANOVO
1913    DAVLEKANOVO
1914    DAVLEKANOVO
Name: city, Length: 1915, dtype: object

In [79]:
df['city_low'] = df['city'].str.lower()

In [80]:
df

,city,email,all_categories,poi_tel,city_low
0,Voronezh,NaN,Fast food joint | Fast food restaurant | Leban...,+7 950 766 66 69,voronezh
1,Vladivostok,NaN,Mailing service,+7 924 251 88 38,vladivostok
2,Ufa,NaN,Mailing service,+7 800 200 58 88,ufa
3,Saratov,NaN,Mailing service | Post Office,+7 800 200 58 88,saratov
4,Москва,NaN,Asset Management | Building Maintenance | Prop...,+7 495 803 33 03,москва
...,...,...,...,...,...
1910,Davlekanovo,NaN,E-commerce Platform | E-commerce Service | Onl...,+7 495 232 10 00,davlekanovo
1911,Davlekanovo,NaN,TV network | TV station | Television channel |...,+7 987 583 43 55,davlekanovo
1912,Davlekanovo,NaN,Business Office | Company Office | Corporate O...,+7 347 683 21 75,davlekanovo
1913,Davlekanovo,NaN,Barber Shop | Barber Supply,+7 927 967 05 36,davlekanovo
1914,Davlekanovo,NaN,Business Park | Commercial Development | Retai...,+7 347 683 17 77,davlekanovo

In [81]:
df['city_low'].value_counts()

city_low
москва                336
санкт-петербург        92
казань                 84
нижний новгород        79
chita                  61
                     ...
ryazanskiy              1
surgut                  1
каменск-шахтинский      1
pavlovskaya             1
rostov oblast           1
Name: count, Length: 143, dtype: int64

In [82]:
df['all_categories'].str.split('|')

0       [Fast food joint ,  Fast food restaurant ,  Le...
1                                       [Mailing service]
2                                       [Mailing service]
3                        [Mailing service ,  Post Office]
4       [Asset Management ,  Building Maintenance ,  P...
                              ...
1910    [E-commerce Platform ,  E-commerce Service ,  ...
1911    [TV network ,  TV station ,  Television channe...
1912    [Business Office ,  Company Office ,  Corporat...
1913                       [Barber Shop ,  Barber Supply]
1914    [Business Park ,  Commercial Development ,  Re...
Name: all_categories, Length: 1915, dtype: object

In [83]:
df['all_categories'].str.split('|', expand=True)

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,Fast food joint,Fast food restaurant,Lebanese Restaurant,Mediterranean Restaurant,Middle Eastern Restaurant,Quick service restaurant,Syrian Eatery,Syrian Restaurant,None,None,...,None,None,None,None,None,None,None,None,None,None
1,Mailing service,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,Mailing service,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,Mailing service,Post Office,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,Asset Management,Building Maintenance,Property Maintenance,Property administration service,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1910,E-commerce Platform,E-commerce Service,Online Retail,Online Store,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1911,TV network,TV station,Television channel,Television network,Television station,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1912,Business Office,Company Office,Corporate Office,Headquarters,Office Space,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1913,Barber Shop,Barber Supply,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1914,Business Park,Commercial Development,Retail Development,Shopping Center,Shopping Mall,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [84]:
df['category_0'] = df['all_categories'].str.split('|', expand=True)[0]
df['category_1'] = df['all_categories'].str.split('|', expand=True)[1]
df['category_2'] = df['all_categories'].str.split('|', expand=True)[2]

In [85]:
df.iloc[0]['category_2']

' Lebanese Restaurant '

In [86]:
len(df.iloc[0]['category_2'])

21

In [87]:
df['category_0'] = df['category_0'].str.strip()
df['category_1'] = df['category_1'].str.strip()
df['category_2'] = df['category_2'].str.strip()

In [88]:
df.iloc[0]['category_2']

'Lebanese Restaurant'

In [89]:
len(df.iloc[0]['category_2'])

19

In [90]:
df['city_low'].value_counts()

city_low
москва                336
санкт-петербург        92
казань                 84
нижний новгород        79
chita                  61
                     ...
ryazanskiy              1
surgut                  1
каменск-шахтинский      1
pavlovskaya             1
rostov oblast           1
Name: count, Length: 143, dtype: int64

In [91]:
df[df['city_low'].str.contains('[a-z]')]['city_low'].value_counts()

city_low
chita            61
ufa              59
voronezh         57
ulyanovsk        53
novosibirsk      51
                 ..
peresyp'          1
kursk             1
surgut            1
rostov oblast     1
pavlovskaya       1
Name: count, Length: 94, dtype: int64

In [92]:
translate_dict = {
    'voronezh':'воронеж',
    'vladivostok':'владивосток',
    'ufa':'уфа',
    'chita':'чита',
    'ulyanovsk':'ульяновск',
    'novosibirsk':'новосибирск',
}

In [93]:
df['city_clean'] = df['city_low']

In [94]:
for eng, rus in translate_dict.items():
    df['city_clean'] = df['city_clean'].str.replace(eng, rus)

In [95]:
df['city_clean']

0           воронеж
1       владивосток
2               уфа
3           saratov
4            москва
           ...
1910    davlekanovo
1911    davlekanovo
1912    davlekanovo
1913    davlekanovo
1914    davlekanovo
Name: city_clean, Length: 1915, dtype: object

In [96]:
df[df['city_clean'].str.contains('[a-z]')]['city_clean'].value_counts()

city_clean
moscow           50
kaluga           46
sochi            41
krasnoyarsk      34
nizhny tagil     25
                 ..
peresyp'          1
kursk             1
surgut            1
rostov oblast     1
pavlovskaya       1
Name: count, Length: 88, dtype: int64

In [141]:
df['poi_tel'].str.extract(r'(\d{3})')

        0
0     950
1     924
2     800
3     800
4     495
...   ...
1910  495
1911  987
1912  347
1913  927
1914  347

[1915 rows x 1 columns]